CREATE TABLE COUNTERS(
    ID SERIAL,
    TYPE VARCHAR(255),
    DELTA BIGINT,
    PRIMARY KEY(ID)
);

CREATE TABLE GAUGES(
    ID SERIAL,
    TYPE VARCHAR(255),
    VALUE DOUBLE PRECISION,
    PRIMARY KEY(ID)
);