// Code generated by protoc-gen-go. DO NOT EDIT.
// source: internal/memtrack/client/rpc/rpc_client.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	wrappers "github.com/golang/protobuf/ptypes/wrappers"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type Gauge struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Value                float64  `protobuf:"fixed64,3,opt,name=value,proto3" json:"value,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Gauge) Reset()         { *m = Gauge{} }
func (m *Gauge) String() string { return proto.CompactTextString(m) }
func (*Gauge) ProtoMessage()    {}
func (*Gauge) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c535664b24ae94f, []int{0}
}

func (m *Gauge) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Gauge.Unmarshal(m, b)
}
func (m *Gauge) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Gauge.Marshal(b, m, deterministic)
}
func (m *Gauge) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Gauge.Merge(m, src)
}
func (m *Gauge) XXX_Size() int {
	return xxx_messageInfo_Gauge.Size(m)
}
func (m *Gauge) XXX_DiscardUnknown() {
	xxx_messageInfo_Gauge.DiscardUnknown(m)
}

var xxx_messageInfo_Gauge proto.InternalMessageInfo

func (m *Gauge) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Gauge) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Gauge) GetValue() float64 {
	if m != nil {
		return m.Value
	}
	return 0
}

func (m *Gauge) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Counter struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Delta                int64    `protobuf:"varint,3,opt,name=delta,proto3" json:"delta,omitempty"`
	Hash                 string   `protobuf:"bytes,4,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Counter) Reset()         { *m = Counter{} }
func (m *Counter) String() string { return proto.CompactTextString(m) }
func (*Counter) ProtoMessage()    {}
func (*Counter) Descriptor() ([]byte, []int) {
	return fileDescriptor_5c535664b24ae94f, []int{1}
}

func (m *Counter) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Counter.Unmarshal(m, b)
}
func (m *Counter) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Counter.Marshal(b, m, deterministic)
}
func (m *Counter) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Counter.Merge(m, src)
}
func (m *Counter) XXX_Size() int {
	return xxx_messageInfo_Counter.Size(m)
}
func (m *Counter) XXX_DiscardUnknown() {
	xxx_messageInfo_Counter.DiscardUnknown(m)
}

var xxx_messageInfo_Counter proto.InternalMessageInfo

func (m *Counter) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Counter) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Counter) GetDelta() int64 {
	if m != nil {
		return m.Delta
	}
	return 0
}

func (m *Counter) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func init() {
	proto.RegisterType((*Gauge)(nil), "rpc.Gauge")
	proto.RegisterType((*Counter)(nil), "rpc.Counter")
}

func init() {
	proto.RegisterFile("internal/memtrack/client/rpc/rpc_client.proto", fileDescriptor_5c535664b24ae94f)
}

var fileDescriptor_5c535664b24ae94f = []byte{
	// 259 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x4f, 0xb1, 0x4a, 0x04, 0x31,
	0x14, 0x24, 0xbb, 0x77, 0x8a, 0x8f, 0xf3, 0x8a, 0x60, 0xb1, 0x1c, 0x22, 0xc7, 0x55, 0xdb, 0x98,
	0x05, 0xed, 0x2c, 0x6c, 0x2c, 0xb4, 0xb1, 0x59, 0x39, 0x2d, 0x25, 0x97, 0x7d, 0xee, 0x05, 0x73,
	0x49, 0x78, 0x9b, 0x55, 0xfc, 0x06, 0x7f, 0x5a, 0x92, 0x9c, 0x9d, 0xe0, 0x15, 0x0f, 0xde, 0x0c,
	0x33, 0xc3, 0x0c, 0x5c, 0x6a, 0x1b, 0x90, 0xac, 0x34, 0xcd, 0x0e, 0x77, 0x81, 0xa4, 0x7a, 0x6f,
	0x94, 0xd1, 0x68, 0x43, 0x43, 0x5e, 0xc5, 0x7b, 0xcd, 0x50, 0x78, 0x72, 0xc1, 0xf1, 0x92, 0xbc,
	0x5a, 0x5c, 0xf4, 0xce, 0xf5, 0x06, 0x9b, 0x44, 0x6d, 0xc6, 0xb7, 0xe6, 0x93, 0xa4, 0xf7, 0x48,
	0x43, 0x16, 0xad, 0xd6, 0x30, 0xbd, 0x97, 0x63, 0x8f, 0x7c, 0x0e, 0x85, 0xee, 0x2a, 0xb6, 0x64,
	0xf5, 0x49, 0x5b, 0xe8, 0x8e, 0x73, 0x98, 0x84, 0x2f, 0x8f, 0x55, 0x91, 0x98, 0xf4, 0xf3, 0x33,
	0x98, 0x7e, 0x48, 0x33, 0x62, 0x55, 0x2e, 0x59, 0xcd, 0xda, 0x0c, 0xa2, 0x72, 0x2b, 0x87, 0x6d,
	0x35, 0xc9, 0xca, 0xf8, 0xaf, 0x5e, 0xe0, 0xf8, 0xce, 0x8d, 0xb1, 0xee, 0xa1, 0xc1, 0x1d, 0x9a,
	0x20, 0x53, 0x70, 0xd9, 0x66, 0xf0, 0x57, 0xf0, 0xd5, 0x37, 0x83, 0xd3, 0x47, 0x0c, 0xa4, 0xd5,
	0x83, 0xb4, 0x9d, 0x41, 0xe2, 0x37, 0x30, 0x5b, 0xfb, 0x4e, 0x06, 0x4c, 0x3b, 0x06, 0x0e, 0x82,
	0xbc, 0x12, 0x09, 0x2c, 0xce, 0x45, 0x9e, 0x2f, 0x7e, 0xe7, 0x8b, 0xa7, 0x40, 0xda, 0xf6, 0xcf,
	0xb1, 0x78, 0xcd, 0xf8, 0x2d, 0xcc, 0xb3, 0x77, 0x5f, 0x76, 0xe0, 0xb3, 0xe4, 0xde, 0xc3, 0xff,
	0xfc, 0x9b, 0xa3, 0xc4, 0x5f, 0xff, 0x04, 0x00, 0x00, 0xff, 0xff, 0x15, 0x85, 0xe7, 0x6d, 0x9a,
	0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MetricHandlerClient is the client API for MetricHandler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MetricHandlerClient interface {
	UpdateGauges(ctx context.Context, opts ...grpc.CallOption) (MetricHandler_UpdateGaugesClient, error)
	UpdateCounters(ctx context.Context, opts ...grpc.CallOption) (MetricHandler_UpdateCountersClient, error)
}

type metricHandlerClient struct {
	cc *grpc.ClientConn
}

func NewMetricHandlerClient(cc *grpc.ClientConn) MetricHandlerClient {
	return &metricHandlerClient{cc}
}

func (c *metricHandlerClient) UpdateGauges(ctx context.Context, opts ...grpc.CallOption) (MetricHandler_UpdateGaugesClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetricHandler_serviceDesc.Streams[0], "/rpc.MetricHandler/UpdateGauges", opts...)
	if err != nil {
		return nil, err
	}
	x := &metricHandlerUpdateGaugesClient{stream}
	return x, nil
}

type MetricHandler_UpdateGaugesClient interface {
	Send(*Gauge) error
	CloseAndRecv() (*wrappers.StringValue, error)
	grpc.ClientStream
}

type metricHandlerUpdateGaugesClient struct {
	grpc.ClientStream
}

func (x *metricHandlerUpdateGaugesClient) Send(m *Gauge) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricHandlerUpdateGaugesClient) CloseAndRecv() (*wrappers.StringValue, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrappers.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *metricHandlerClient) UpdateCounters(ctx context.Context, opts ...grpc.CallOption) (MetricHandler_UpdateCountersClient, error) {
	stream, err := c.cc.NewStream(ctx, &_MetricHandler_serviceDesc.Streams[1], "/rpc.MetricHandler/UpdateCounters", opts...)
	if err != nil {
		return nil, err
	}
	x := &metricHandlerUpdateCountersClient{stream}
	return x, nil
}

type MetricHandler_UpdateCountersClient interface {
	Send(*Counter) error
	CloseAndRecv() (*wrappers.StringValue, error)
	grpc.ClientStream
}

type metricHandlerUpdateCountersClient struct {
	grpc.ClientStream
}

func (x *metricHandlerUpdateCountersClient) Send(m *Counter) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricHandlerUpdateCountersClient) CloseAndRecv() (*wrappers.StringValue, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(wrappers.StringValue)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// MetricHandlerServer is the server API for MetricHandler service.
type MetricHandlerServer interface {
	UpdateGauges(MetricHandler_UpdateGaugesServer) error
	UpdateCounters(MetricHandler_UpdateCountersServer) error
}

// UnimplementedMetricHandlerServer can be embedded to have forward compatible implementations.
type UnimplementedMetricHandlerServer struct {
}

func (*UnimplementedMetricHandlerServer) UpdateGauges(srv MetricHandler_UpdateGaugesServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateGauges not implemented")
}
func (*UnimplementedMetricHandlerServer) UpdateCounters(srv MetricHandler_UpdateCountersServer) error {
	return status.Errorf(codes.Unimplemented, "method UpdateCounters not implemented")
}

func RegisterMetricHandlerServer(s *grpc.Server, srv MetricHandlerServer) {
	s.RegisterService(&_MetricHandler_serviceDesc, srv)
}

func _MetricHandler_UpdateGauges_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricHandlerServer).UpdateGauges(&metricHandlerUpdateGaugesServer{stream})
}

type MetricHandler_UpdateGaugesServer interface {
	SendAndClose(*wrappers.StringValue) error
	Recv() (*Gauge, error)
	grpc.ServerStream
}

type metricHandlerUpdateGaugesServer struct {
	grpc.ServerStream
}

func (x *metricHandlerUpdateGaugesServer) SendAndClose(m *wrappers.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricHandlerUpdateGaugesServer) Recv() (*Gauge, error) {
	m := new(Gauge)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _MetricHandler_UpdateCounters_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricHandlerServer).UpdateCounters(&metricHandlerUpdateCountersServer{stream})
}

type MetricHandler_UpdateCountersServer interface {
	SendAndClose(*wrappers.StringValue) error
	Recv() (*Counter, error)
	grpc.ServerStream
}

type metricHandlerUpdateCountersServer struct {
	grpc.ServerStream
}

func (x *metricHandlerUpdateCountersServer) SendAndClose(m *wrappers.StringValue) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricHandlerUpdateCountersServer) Recv() (*Counter, error) {
	m := new(Counter)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MetricHandler_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.MetricHandler",
	HandlerType: (*MetricHandlerServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "UpdateGauges",
			Handler:       _MetricHandler_UpdateGauges_Handler,
			ClientStreams: true,
		},
		{
			StreamName:    "UpdateCounters",
			Handler:       _MetricHandler_UpdateCounters_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "internal/memtrack/client/rpc/rpc_client.proto",
}
